sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "8"
after_script: npm run send-coverage
script: npm run lint && npm test && npm run spec
after_success:
  - npm run semantic-release
git:
  depth: 1
